-- migrations/002_works.up.sql

START TRANSACTION;
CREATE TABLE IF NOT EXISTS `works` (
  `id`         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `author_id`  INT UNSIGNED NOT NULL,
  `title`      VARCHAR(255) NOT NULL,
  `body`       TEXT          NOT NULL,
  `created_at` TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
COMMIT;
